# betterm PowerShell profile: a violet (pwd) + pink (git branch) powerline prompt,
# plus the startup banner generated by betterm. Auto-loaded inside betterm; it does
# not touch your global $PROFILE.

function global:prompt {
    $e = [char]27
    $reset    = "$e[0m"
    $violetBg = "$e[48;2;138;43;226m"
    $pinkBg   = "$e[48;2;255;105;180m"
    $white    = "$e[38;2;255;255;255m"
    $violetFg = "$e[38;2;138;43;226m"
    $pinkFg   = "$e[38;2;255;105;180m"
    $sep      = [char]0xE0B0   # powerline separator

    $p = $PWD.Path
    if ($p.StartsWith($env:USERPROFILE)) {
        $p = '~' + $p.Substring($env:USERPROFILE.Length)
    }

    $folder = [char]0xF07C
    $line = "$violetBg$white $folder $p $reset"

    $branch = git rev-parse --abbrev-ref HEAD 2>$null
    if ($LASTEXITCODE -eq 0 -and $branch) {
        $line += "$violetFg$pinkBg$sep$reset"
        $line += "$pinkBg$white $([char]0xE0A0) $branch $reset"
        $line += "$pinkFg$sep$reset"
    } else {
        $line += "$violetFg$sep$reset"
    }

    return "$line`n$white❯ $reset"
}

# Print the betterm-generated system-info banner (same file for every shell).
if ($env:BETTERM_BANNER -and (Test-Path -LiteralPath $env:BETTERM_BANNER)) {
    [Console]::Out.Write([IO.File]::ReadAllText($env:BETTERM_BANNER))
}
