# betterm Git Bash init. betterm launches `bash --rcfile <this> -i`, so we first
# restore the normal environment (login profile + user bashrc), then print the
# betterm system-info banner.

[ -f /etc/profile ] && . /etc/profile
[ -f "$HOME/.bash_profile" ] && . "$HOME/.bash_profile"
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"

# System-info banner generated by betterm (path passed via env, forward slashes).
if [ -n "$BETTERM_BANNER" ] && [ -f "$BETTERM_BANNER" ]; then
    cat "$BETTERM_BANNER"
fi
